services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: "myadminuser"
      MINIO_ROOT_PASSWORD: "mysecurepassword"
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data
    command: server /data
    restart: always
    networks:
      - backend2
    healthcheck:
      test: ["CMD", "mc", "alias", "set", "myminio", "http://localhost:9000", "myadminuser", "mysecurepassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - backend2
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgresUser:
    image: postgres:latest
    container_name: postgres_user_container
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "070823"
      POSTGRES_DB: "users"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-user:/var/lib/postgresql/data
    networks:
      - backend2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  serviceUser:
    image: service_user:latest
    container_name: serviceUser
    ports:
      - "8080:8080"
    depends_on:
      postgresUser:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      USER_SERVICE: ":8080"
      DATABASE_URL: "postgres://postgres:070823@postgres_user_container:5432/users?sslmode=disable"
      REDIS_ADDR: "redis:6379"
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ROOT_USER: "myadminuser"
      MINIO_ROOT_PASSWORD: "mysecurepassword"
      S3_BUCKET: "my-bucket"
    networks:
      - backend2
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  backend2:
    external: true

volumes:
  postgres-data-user:
  minio-data:
