services:
  serviceNotification:
    image: service_notification:latest
    container_name: serviceNotification
    environment:
      TELEGRAM_BOT_TOKEN: ""
      KAFKA_URL: "kafka:9092"
      KAFKA_LIKE_TOPIC: "likes-topic"
      GROUP_ID: "test-group"
      USER_SERVICE: "http://serviceUser:8080"
    networks:
      - backend2
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  backend2:
    external: true
